### PR TITLE
Update frontend tooling to use Node 20

### PR DESCRIPTION
**Pull request by lb-**
Ensure we are on the latest LTS of Node for frontend tooling.

See https://github.com/wagtail/wagtail/pull/11141 (Wagtail core update)

### CODE REVIEW

**Comment by lb-** [comment]
OK this may be blocked by Vercel not supporting Node 20 yet.

Screenshot 2023-11-12 at 3 18 01 pm

https://vercel.com/docs/functions/serverless-functions/runtimes/node-js#node.js-version

https://github.com/vercel/pkg/discussions/1972

**Comment by lb-** [comment]
Ok. We might be able to use Node 20 now in Vercel. 

https://vercel.com/changelog/nodejs-20

**Comment by lb-** [comment]
OK not sure here, will have to review again later.

```
Warning: Detected "engines": { "node": ">=20" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
```

```
Error: Command "npm install && python3 -m pip install -r requirements.txt && pip install "urllib3<2" && python3 -m pip install -e ." exited with 1
```

**Comment by laymonage** [comment]
Oops, I didn't see that we don't use Node 20 yet. I updated the RTD config to use Node 20, builds OK (with some warnings) but I assume we'll want to update it anyway.

**Comment by lb-** [comment]
I think that's fine, it's just Vercel taking a bit to make their Node 20 support official.

**Pull request merged**
